import { Inter } from "next/font/google";
import "./styles/globals.css";
import "./styles/themes.css";
import "./index.css";
import Layout from "./components/Layout";
import Head from "./components/Head";
import ThemeProvider from "./components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shifyan Almustafid",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <Head title={`Shifyan Almustafid`}></Head>
          <ThemeProvider />
          {children}
        </Layout>
      </body>
    </html>
  );
}
